# Generated by Django 5.1.5 on 2025-01-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0013_program_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_budget',
        ),
    ]
