# Generated by Django 5.1.5 on 2025-01-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0014_remove_project_latitude_remove_project_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#cc1631', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#cc1631', max_length=7)),
                ('image', models.ImageField(upload_to='resource_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='resource_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcedetails', to='Hope.program')),
            ],
        ),
    ]
