# Generated by Django 5.1.5 on 2025-01-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0016_alter_resourcedetail_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedetail',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceDetails', to='Hope.resource'),
        ),
    ]
