# Generated by Django 5.1.2 on 2025-02-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0018_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
