# Generated by Django 5.1.2 on 2025-02-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0019_program_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_image',
        ),
    ]
