# Generated by Django 5.1.2 on 2025-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0020_remove_volunteer_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='self_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
