# Generated by Django 5.1.2 on 2025-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0021_remove_volunteer_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedetail',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
